services:
  find-my-api:
    image: rayhanadev/find-my-api:latest
    container_name: find-my-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./.icloud:/app/.icloud
